Initial implement of fuse check
UBCFormulaElectric/Consolidated-Firmware pull request #1005
Opened 2023-10-06 05:55 UTC by KelmLelm

### Summary

Initial implementation for a fuse check in App_Accumulator (Battery Cells)
### Changelist 

App_Accumulator.c added the blown fuse check code in CheckFaults,  BMS_Alert.json added blown fuse fault.
### Testing Done

Just initial implementation. Nothing yet.
### Resolved Issues

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [ ] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [ ] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

2023-10-06 06:07 UTC, KelmLelm commented
Like the description says, just an initial draft of implementation, not unit tested yet

2023-10-07 05:27 UTC, gtaharaedmonds commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
Can you provide some way of linking to where you got this number? LiIon cell part number + link to datasheet would be great.

2023-10-07 05:46 UTC, gtaharaedmonds requested changes
Great first draft!
We should add a unit test for this too.

2023-10-07 05:46 UTC, gtaharaedmonds commented on can_bus/json/BMS/BMS_alerts.json
> +        "BMS_FAULT_BLOWN_CELL_FUSE"
Can you make this a warning instead? Faults will cause the car to shutdown so until this is reliable I don't want the car to shutdown unnecessarily. Also I don't think fuses blowing is a high enough risk to make this a fault at present.

2023-10-07 05:46 UTC, gtaharaedmonds commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
>      // if we are charging, max cell temp is 45C not 60C
Can you move this block to a helper function? I think it'd be a bit more readable.

2023-10-07 05:46 UTC, gtaharaedmonds commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
> +                        (cell_voltage_avg - cell_voltage_minimum + segment_current*INTERNAL_CELL_RESISTANCE_OHMS/3.0);
Hmm I don't think `cell_voltage_minimum` and `cell_voltage_avg` are what we want. 

It looks like `cell_voltage_minimum` is the minimum of the average cell voltages for each segment - you want the individual cell with the lowest voltage. This info is in the `accumulator->voltage_status.min_voltage` variable.

`cell_voltage_avg` is `cell_voltage_sum` divided by 4? where does this come from?

2023-10-07 05:46 UTC, gtaharaedmonds commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
> +                        (cell_voltage_avg - cell_voltage_minimum + segment_current*INTERNAL_CELL_RESISTANCE_OHMS/3.0);
`num_of_cells` isn't super descriptive - maybe `estimated_min_cells_in_parallel`?

2023-10-07 05:46 UTC, gtaharaedmonds commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
> +    bool blown_fuse_fault = num_of_cells < 2.5;
make a macro for this 2.5 value at the top - also maybe drop a TODO about needing to do testing on the car to determine this 2.5 number. 
(unnecessary if we're going to determine that before we merge this in, but then you should write something about where the number comes from)

2023-10-07 05:46 UTC, gtaharaedmonds commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
> +    App_CanAlerts_SetFault(BMS_FAULT_BLOWN_CELL_FUSE, blown_fuse_fault);
We should also add a CAN signal indicating the estimated min. number of cells in parallel, as well as the corresponding cell/segment

2023-10-07 05:47 UTC, gtaharaedmonds commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
> +                        (cell_voltage_avg - cell_voltage_minimum + segment_current*INTERNAL_CELL_RESISTANCE_OHMS/3.0);
Also this math isn't super obvious - maybe link to the confluence doc?

2023-10-07 05:49 UTC, gtaharaedmonds commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
> +                        (cell_voltage_avg - cell_voltage_minimum + segment_current*INTERNAL_CELL_RESISTANCE_OHMS/3.0);
Also also can you add a check to make sure we don't actually divide by zero? I don't think its possible but I don't want the board to crash if that ever does magically happen...

2023-11-03 17:40 UTC, will-chaba reviewed
Looks good so far!

2023-11-03 17:40 UTC, will-chaba commented on firmware/thruna/BMS/Inc/App/App_Accumulator.h
> +#define ACCUMULATOR_NUM_CELLS_PER_SEGMENT (3U)
```suggestion
#define ACCUMULATOR_NUM_PARALLEL_CELLS (3U)
```

2023-11-03 17:40 UTC, will-chaba commented on firmware/thruna/BMS/Src/App/states/App_AllStates.c
> +        // Cut torque requests to wheels??
For now, warnings are only displayed to the driver for them to act on, if we can confirm that this algorithm does not produce false-positives, could potentially look into either cutting torque or upgrading to a fault.

2023-11-03 17:40 UTC, will-chaba commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
> +#define FUSE_CHECK_CURRENT_THRESHOLD (40.0f)
Always good to specify units where applicable:
```suggestion
#define FUSE_CHECK_CURRENT_THRESHOLD_AMPS (40.0f)
```

2024-04-13 18:19 UTC, will-chaba commented on firmware/thruna/BMS/Src/App/App_Accumulator.c
> +#define FUSE_CHECK_CURRENT_THRESHOLD_AMPS (40.0f)
will need to lower current threshold for testing

2024-06-12 02:34 UTC, will-chaba commented
Out of date

2024-06-12 02:34 UTC, closed without merging