Latching faults and warnings
UBCFormulaElectric/Consolidated-Firmware pull request #1024
Opened 2023-10-13 18:40 UTC by gtaharaedmonds

### Summary

Faults and warnings (finally) latch. This is implemented in another CAN message for faults and warnings, which counts the number of times an alert is set. Each count gets 3 bits for  a maximum count of 7. This also means the maximum number of faults or warnings is reduced from 64 to 21, since currently we just pack all faults/warnings counts into a single CAN message and so can only fit 21 counts for a total of 63 bits.

So:

- `<board>_Faults` is unchanged (still describes the current status of each fault
- `<board>_FaultCounts` allocates a 3-bit counter for each fault, which count the number of rising edge transitions (no fault -> fault)

(and similarly for warnings)

### Changelist 

- Implement fault/warning counts as described above and fix tests
- Change the alert settings syntax to be more similar to `App_CanTx`/`App_CanRx`

### Testing Done

- [x] Spun wheels on jacks

### Resolved Issues

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [x] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [x] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

2023-10-15 18:16 UTC, Lucien950 requested changes
a few small changes requested, otherwise builds just fine on a rebase

2023-10-15 18:17 UTC, Lucien950 commented
I noticed that alerts also interface with the same tx functions that can messages use, meaning that it is possible to set alerts while bypassing `App_CanAlerts...`. Should we move the logic for alert table mutation inside `App_CanAlerts.c`?

2023-10-24 00:25 UTC, gtaharaedmonds commented on scripts/code_generation/jsoncan/src/codegen/c_generation/app_can_alerts_module.py
> +        funcs.extend(self._get_alert_funcs(CanAlertType.FAULT))
Yep exactly.

2023-10-24 00:26 UTC, gtaharaedmonds commented on scripts/code_generation/jsoncan/src/json_parsing/json_can_parsing.py
>                  ]
Spread operator is sexier

2023-10-24 00:28 UTC, gtaharaedmonds commented on scripts/code_generation/jsoncan/src/json_parsing/schema_validation.py
> +            "faults_counts_id": And(int, lambda x: x >= 0),
good call, added

2023-10-24 00:34 UTC, gtaharaedmonds commented
> I noticed that alerts also interface with the same tx functions that can messages use, meaning that it is possible to set alerts while bypassing `App_CanAlerts...`. Should we move the logic for alert table mutation inside `App_CanAlerts.c`?

Yeah this is a fair concern, in fact we are currently already doing this in one or two places (fixed in my last PR). The alert signals are parsed as regular CAN signals, so that they're in the DBC and the pack/unpack functions are generated (like the rest of the CAN signals). This makes them very tightly coupled with the rest of the CAN system, so uncoupling them will be hard. As such I don't want to do this right now since latching faults is very high priority, maybe make a Jira ticket to look into this later?

2023-10-24 07:11 UTC, Lucien950 approved these changes
i ain't really check `can_bus/json` and `firmware/thruna` like that but python is cooking

2023-10-24 19:36 UTC, merged