Kyle/torque vectoring
UBCFormulaElectric/Consolidated-Firmware pull request #1049
Opened 2023-10-21 22:51 UTC by 1mackenziekyle

### Summary

### Changelist 

### Testing Done
Car testing and unit testing

### Resolved Issues

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [ ] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [ ] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

2023-10-31 00:09 UTC, philam2001 requested changes

2023-11-04 23:26 UTC, 1mackenziekyle commented on environment/Dockerfile
> -COPY . /root/environment/
@gtaharaedmonds is this file stilled used?

2023-11-04 23:27 UTC, 1mackenziekyle commented on typescript
@gtaharaedmonds is this file still used too?

2023-11-05 00:27 UTC, philam2001 requested changes

2023-11-05 00:41 UTC, 1mackenziekyle commented on build
> +#!/bin/bash
@gtaharaedmonds I don't know why this is modified, I think it might have to do with Docker issues from a while ago??

2023-11-06 07:23 UTC, gtaharaedmonds reviewed
let's goo it looks almost ready to go in
mostly just had recommendations for documentation
also looks like tests are failing

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Src/App/torquevectoring/App_TorqueVectoring.c
> +    available_battery_power_kW = 44.0f; // Tentative
Where does this number come from?

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Src/App/torquevectoring/App_TorqueVectoring.c
> +    power_limit       = estimated_power_limit * (1.0f + pid_power_correction_factor);
this can be 1 line

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Src/App/torquevectoring/App_TorqueVectoring.c
> +     * SKIP TRACTION CONTROL FOR NOW
Maybe add some more info here, i.e. hasn't been tested on the car

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Src/App/torquevectoring/App_TorqueVectoring.c
Maybe dump a README in this folder with a super quick overview (just a few sentences would be fine with me) about the algorithm and the code structure. And also a link to the Confluence page.

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Test/Src/torquevectoring/Test_ActiveDifferential.cpp
> +    ASSERT_FLOAT_EQ(expected_ratio_t1, actual_ratio_t1);
These are basically impossible to understand, however I get that its a complicated algorithm and so hard to unit test effectively. However, can you at least add a line on what each test function is actually confirming?

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Test/Src/torquevectoring/Test_PowerLimiting.cpp
> + */
Comments like these are great

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Test/Src/torquevectoring/Test_PowerLimiting.cpp
> +    // PowerLimiting_Inputs));
Remove

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Test/Src/torquevectoring/Test_ActiveDifferential.cpp
> +    ASSERT_FLOAT_EQ(expected_ratio_t1, actual_ratio_t1);
Here and other test files too

2023-11-06 07:23 UTC, gtaharaedmonds commented on firmware/thruna/DCM/Src/App/torquevectoring/App_TorqueVectoring.c
> +    //                             POWER_TO_TORQUE_CONVERSION_FACTOR;
Delete or add some info on why this is commented out

2023-11-18 20:28 UTC, gtaharaedmonds approved these changes

2024-01-13 19:23 UTC, philam2001 approved these changes

2024-01-13 19:23 UTC, merged