Matthew yung/websocket integration
UBCFormulaElectric/Consolidated-Firmware pull request #1073
Opened 2023-11-05 21:23 UTC by myung03

##Summary
Refactored code, added websockets back, and finished typing for new components

##Changelist 
###BUGS 
- Fixed synchronous zoom bug where graphs would be synced on initial mount even when sync was false 
- Fixed Websockets returning data to all live graphs

###FEATURES 
- Re-implemented web sockets! 
- Added mock live data functionality to test data visualization (can turn on and off) 
- Refactored code in more modular packages 
    - on frontend -> folder for live data graph components, folder for db graph components, visualize/dashboard component for page (before all rendering was done in page 
    - On backend -> separated functions different files dependent on if they were db related/websocket related 
    - Finished typing new components
- Added dark mode
- Added styling changes

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [x] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [x] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

2023-11-06 19:50 UTC, Evanyl commented
This dude is crazyy 🔥

2023-11-06 21:39 UTC, forbesashli approved these changes
looks great to me! really enjoy the dark mode and the changes, yeehaw

2023-11-06 21:39 UTC, forbesashli commented on software/tracksight/frontend/src/app/components/navbar.tsx
love the dark mode, however it is hard my eyes (personally, I have bad eyes LOL) maybe in the future have the ability to toggle

2023-11-06 21:42 UTC, forbesashli requested changes
Your code looks great, really like the dark mode addition. However the tests arent passing for the lower level (strange). In good practice we should investigate but it is probably an update of sorts

2023-11-09 22:31 UTC, jpatch22 approved these changes
LGTM after rebasing

2023-11-09 22:31 UTC, jpatch22 commented on software/tracksight/backend/app/process/SignalUtil.py
> +                # print(self.df.head())
Let's just delete this, can do it in here or I can do it somewehere else

2023-11-10 04:07 UTC, jpatch22 requested changes

2023-11-10 04:07 UTC, jpatch22 commented on firmware/dev/f4dev/src/cubemx/Inc/FreeRTOSConfig.h
> +/* USER CODE BEGIN Header */
Looks like some firmware stuff got added? Probably some git weirdness....

2023-11-17 01:12 UTC, closed without merging