CAN Bootloader
UBCFormulaElectric/Consolidated-Firmware pull request #1083
Opened 2023-11-11 02:34 UTC by gtaharaedmonds

### Summary

### Changelist 

### Testing Done

### Resolved Issues

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [ ] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [ ] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

2023-11-16 07:37 UTC, Lucien950 commented
![image](https://github.com/UBCFormulaElectric/Consolidated-Firmware/assets/20777515/2262083d-f62a-4f5d-8fef-74833369cf91)
what's up with all these new targets?

2023-11-16 07:39 UTC, Lucien950 requested changes
I couldn't highlight it in the review section cause it's a submodule, but can you also add the requirements.txt to the requiremnets.txt in the environment folder, and Pipenv?

2023-11-16 07:42 UTC, Lucien950 commented
Also python command documentation pls because I want to have a Clion config for Python I can add here.

2023-11-17 18:12 UTC, will-chaba approved these changes
Fix tests and maybe add some newlines at end of files

2023-11-17 19:11 UTC, Lucien950 commented on can_bus/json/shared_enum.json
> +        "BOOT_STATUS_APP_VALID": 2
probably better to make happy state 0, and natural numbers error codes.

2023-11-22 05:32 UTC, merged