FSM Tweaks
UBCFormulaElectric/Consolidated-Firmware pull request #1230
Opened 2024-04-09 00:32 UTC by liam-ilan

### Changelist 
- Fixed bug related to apps/brakes conflict not checking secondary apps.

### Testing Done
- Passes unit tests

### Resolved Tickets

2024-04-14 07:00 UTC, Lucien950 requested changes
given CI I don't think the PWM will have any conflicts with the rest of the boards. So that's good I hope...

https://www.digitalocean.com/community/tutorials/arrow-operator-c-plus-plus

especially the `config`s. Remember that dereferences cost additional stack memory + cycles (very minimal).

Otherwise I am very happy to merge.

2024-04-14 07:01 UTC, Lucien950 commented
also it also looks like thruna FSM build is failing because we are sharing code? Perhaps split it off (but we are rm/rfing soon anyways)

2024-04-15 06:34 UTC, liam-ilan commented on firmware/quadruna/FSM/src/io/io_wheels.c
> -#include "main.h"
fixed arrow thing!

2024-04-15 06:36 UTC, liam-ilan commented
> also it also looks like thruna FSM build is failing because we are sharing code? Perhaps split it off (but we are rm/rfing soon anyways)
Known issue that thruna FSM build fails since pwm configs are handled differently now, I can migrate thruna fsm to the new configs, though there isn't much of a use keeping it updated anymore. LMK what you want me to do :D

2024-04-15 06:46 UTC, Lucien950 approved these changes
![Uploading image.png…]()

2024-04-15 20:11 UTC, merged