SOC on SD Card
UBCFormulaElectric/Consolidated-Firmware pull request #1233
Opened 2024-04-09 18:25 UTC by DJ90864

### Changelist 
Moved to SD to store SOC values
CRC peripheral enabled for SOC data integrity

### Testing Done
SD card operations are tested with different SOC values on Quadruna
Custom Reset needs to be tested since there was an issue with the CAN Rx signal

### Resolved Tickets

2024-04-09 19:26 UTC, will-chaba commented on firmware/quadruna/BMS/src/app/app_soc.c
> +#ifdef TARGET_EMBEDDED
Why not wrap the entire function? Is there a testable benefit to leaving the above 3 lines in?

2024-04-10 09:23 UTC, Jiajun-Huang requested changes

2024-04-20 06:05 UTC, DJ90864 commented on firmware/shared/src/hw/hw_sd.c
> +}
done!

2024-04-20 06:06 UTC, DJ90864 commented on firmware/quadruna/BMS/src/cubemx/Src/main.c
> +    HAL_SD_ConfigWideBusOperation(&hsd1, SDMMC_BUS_WIDE_4B);
done!

2024-04-20 13:59 UTC, DJ90864 commented on firmware/shared/src/hw/hw_sd.c
makes sense!
I moved it from hw_sd to app_soc instead.

2024-04-22 16:25 UTC, Jiajun-Huang requested changes
Just rm the GPIO  stuff from hw_sd. Others are good!

2024-04-22 16:25 UTC, Jiajun-Huang commented on firmware/shared/src/hw/hw_sd.h
> +#include "hw_gpio.h"
Can you remove the gpio stuff from hw_sd?

2024-04-22 16:25 UTC, Jiajun-Huang commented on firmware/shared/src/hw/hw_sd.h
> +bool hw_sd_checkSdPresent(void);
remove here

2024-04-22 16:25 UTC, Jiajun-Huang commented on firmware/shared/src/hw/hw_sd.h
> +bool hw_sd_sdReady(void);
also here

2024-04-22 16:25 UTC, Jiajun-Huang commented on firmware/shared/src/hw/hw_sd.c
>  }
I guess here is also not needed

2024-04-30 07:04 UTC, Jiajun-Huang approved these changes

2024-05-05 07:41 UTC, will-chaba approved these changes
Looks good to me! Tested functional on BMS May 5, 2024

2024-05-05 07:41 UTC, will-chaba commented on firmware/quadruna/BMS/src/app/app_soc.c
> +        // anything to do if fail to read it corrrectly from the SD?
Everything that needs to be done is done already, set SOC corrupt and set SOC to -1 to signify it needs to be reset based on cell voltage

2024-05-05 10:34 UTC, merged