Tracksight refactor 3
UBCFormulaElectric/Consolidated-Firmware pull request #1333
Opened 2024-08-24 21:01 UTC by myung03

### Changelist 
Note that this a draft PR (i.e WIP), will open PR once complete (hopefully EOD!)
* Added path aliases for lib and ui (i.e to import particular ui component, import { Sonner } from @ts/ui)
* Restructured to move small ui components into a global package to be accessed from anywhere
* Added sonner, clsx, cva, tailwindmerge, tailwindanimate, shadcn, etc.
* Use Next.js built in navigation page structure
* Folders now contain page and associated component (visualize, dashboard, etc.), as well as any larger, non reusable components
* use ThemeProvider to handle light/dark mode
* update README
* small code style things to make code more readable
### Testing Done
* UI Testing to ensure that functionality remains the same. Only frontend changes were made; frontend logic/backend is unchaged. 
* Only Navbar has changed visually as navigation is now handled properly by Next.js.

2024-08-26 02:14 UTC, Lucien950 commented on software/tracksight/frontend/src/app/globals.css
> +@tailwind utilities;
duplicate?

2024-08-26 03:36 UTC, Lucien950 requested changes
love the new organization and the prettier formatting. Few more things before we merge; after this PR I think we should start looking towards next year and longer term to see what is in store there.

2024-08-26 03:36 UTC, Lucien950 commented on software/tracksight/frontend/src/app/visualize/influxcomponents/query_data.tsx
> +    <div style={{ display: "flex", flexDirection: "column" }}>
tailwind?

2024-08-28 05:06 UTC, myung03 commented on software/tracksight/frontend/src/app/navbar.tsx
> +        <Menu
agree, I think that'll be one of the first things I work on while we start adding more features!

2024-08-28 05:11 UTC, myung03 commented on software/tracksight/frontend/tsconfig.json
>      "paths": {
added, shortcut is "~"

2024-08-28 14:25 UTC, Lucien950 approved these changes

2024-08-28 14:25 UTC, Lucien950 commented on software/tracksight/frontend/src/app/globals.css
> +@tailwind utilities;
```suggestion
```

2024-08-30 03:49 UTC, merged