Regen Pedal Remap and Hysteresis Derate
UBCFormulaElectric/Consolidated-Firmware pull request #1351
Opened 2024-10-15 06:12 UTC by philam2001

### Changelist 

### Testing Done

### Resolved Tickets

2025-01-19 19:38 UTC, Lucien950 requested changes
few questions

2025-01-19 19:38 UTC, Lucien950 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +static bool                      regen_enabled       = true;
why is this a static variable? can we just have a function which determines it? I worry about stale information

2025-01-19 19:38 UTC, Lucien950 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +    // Hysterisis
this this hysterisis or does it just cut it off < 7kph?

2025-01-19 19:38 UTC, Lucien950 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +        return apps_pedal_percentage / (MAX_PEDAL_PERCENT - PEDAL_SCALE - 0.1f);
i don't think this is right, I think you need to
```suggestion
        return (apps_pedal_percentage-0.1f) / (MAX_PEDAL_PERCENT - PEDAL_SCALE - 0.1f);
```

2025-01-19 19:38 UTC, Lucien950 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +        return apps_pedal_percentage / (MAX_PEDAL_PERCENT - PEDAL_SCALE - 0.1f);
because this assumes that the increasing part of the graph is rooted at the origin

2025-01-31 23:36 UTC, philam2001 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +static bool                      regen_enabled       = true;
initialized once at the beginning and persists between calls until we change it `wheelSpeedInRange`. I think you would want this to make sure you have the last condition the car state was in for hysterisis? what stale info do u mean

2025-01-31 23:36 UTC, philam2001 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +    // Hysterisis
it'll cut off at 5kph if you were regening before and then start back up again after 7kph

2025-01-31 23:49 UTC, philam2001 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +        return apps_pedal_percentage / (MAX_PEDAL_PERCENT - PEDAL_SCALE - 0.1f);
fak i should write tests for this

2025-02-12 04:08 UTC, Lucien950 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +        regenAttr->derating_value = regenAttr->derating_value * (min_motor_speed_rpm - SPEED_MIN_kph) / SPEED_MIN_kph;
2 units here?

2025-03-01 18:23 UTC, philam2001 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +        regenAttr->derating_value = regenAttr->derating_value * (min_motor_speed_rpm - SPEED_MIN_kph) / SPEED_MIN_kph;
mb

2025-03-01 20:20 UTC, philam2001 commented on firmware/quadruna/VC/src/app/vehicle_dynamics/app_regen.c
> +        regenAttr->derating_value = regenAttr->derating_value * (min_motor_speed_rpm - SPEED_MIN_kph) / SPEED_MIN_kph;
wdym clamp

2026-05-03 00:28 UTC, Lucien950 commented
regen changes in new algo

2026-05-03 00:28 UTC, closed without merging