Mattiasjack/bms diagnostics mode
UBCFormulaElectric/Consolidated-Firmware pull request #1367
Opened 2024-10-29 01:20 UTC by mattiaswong6

### Changelist 
BMS Diagnostics Mode WIP for check-in review.
Fully implemented diagnostics mode for Segment 0. Broadcasts cell voltages and temps when diagnostics broadcast function called in mainState.

### Testing Done
No testing done. Currently trying to write GTest tests.

### Resolved Tickets

2024-11-08 19:52 UTC, DJ90864 commented on can_bus/quadruna/Debug/Debug_tx.json
> +            "CellDiagnosticsRequest": {
use "SegmentCellVoltageRequest" or something similar to show its cell voltages

2024-11-08 20:21 UTC, DJ90864 commented on firmware/quadruna/BMS/src/app/app_diagnosticsMode.c
> +    app_diagnosticsMode_calculateDiagnosticVoltageStats();
```suggestion
bool cellVoltageDiagnosticEnabled = app_canRx_Debug_CellVoltageDiagnoticEnabled_get();
if( cellVoltageDiagnoticEnabled){
    app_diagnosticsMode_calculateDiagnosticVoltageStats();
    }
```
Only calculate the Diagnotic stats if the the diagnotic mode is enabled to make it more efficient in normal operation.
Instead add a bool for cell voltage diagnostic mode to the CAN message to enable or disable the stats calculation

Its already this way for Temp Diagnostic Mode.

2024-11-08 20:24 UTC, DJ90864 commented on firmware/quadruna/BMS/src/app/states/app_allStates.c
> +    bool diagnostics_mode_enabled = app_canRx_Debug_CellDiagnosticsRequest_get();
```suggestion
    bool diagnostics_mode_enabled = app_canRx_Debug_CellDiagnosticsRequest_get();
```

This variable isn't bool in the Debug_tx.json anymore (its an enum rn)

2024-11-08 20:28 UTC, DJ90864 requested changes
Great work so far, please check the comments I left
Also, please test this on the car before merging.

2024-11-10 21:40 UTC, Lucien950 requested changes

2024-11-10 21:40 UTC, Lucien950 commented on firmware/quadruna/BMS/test/test_diagnosticsMode.cpp
> +    SetUp();
teardown and setup should be automatically called by the test fixture

2024-11-10 21:40 UTC, Lucien950 commented on can_bus/quadruna/BMS/BMS_tx.json
> +
```suggestion
```

2024-11-10 21:40 UTC, Lucien950 commented on can_bus/quadruna/Debug/Debug_tx.json
> +            }
is the idea here to choose which segment specifically you want to debug and only show information about that segment? If so, all messages are currently configured to broadcast all the time (as per BMS_tx.json)

2024-11-10 21:40 UTC, Lucien950 commented on firmware/quadruna/BMS/src/app/states/app_allStates.c
> +    }
i think we need to have a chat about how jsoncan works...

2025-01-19 19:11 UTC, Lucien950 requested changes
few more things

2025-01-19 19:11 UTC, Lucien950 commented on firmware/quadruna/BMS/src/app/app_diagnosticsMode.h
> +void app_diagnosticsMode_calculateDiagnosticTemperatureStats(void);
does this need to be a public function?

2025-02-20 18:52 UTC, mattiaswong6 commented
Tested on car Feb. 19. Working as intended.

2025-02-25 03:17 UTC, DJ90864 approved these changes
LGTM!

2025-03-13 18:18 UTC, Lucien950 approved these changes

2025-03-15 17:07 UTC, merged