C++ StackWatermark
UBCFormulaElectric/Consolidated-Firmware pull request #1373
Opened 2024-11-05 02:28 UTC by Lucien950

### Changelist 

### Testing Done

### Resolved Tickets

2024-11-05 04:14 UTC, Lucien950 commented on firmware/quintuna/CRIT/src/cubemx/Src/main.c
> +#include "../../../../../shared/src/io/io_log.h"
```suggestion
```

2024-11-09 22:07 UTC, liam-ilan requested changes
Looks good to me!

2024-11-09 22:07 UTC, liam-ilan commented on firmware/quintuna/CRIT/src/app/app_stackMonitorConfig.h
> +inline StackMonitor<5> crit_stack_monitor{
Nit - I think it's cleaner to specify the `stack_monitor_config` type explicitly for all items.

2024-11-10 01:27 UTC, AmirTajaddodi approved these changes
LGTM!!

2024-11-10 07:23 UTC, merged