Chimera Watchdog Repair
UBCFormulaElectric/Consolidated-Firmware pull request #1379
Opened 2024-11-09 21:57 UTC by liam-ilan

### Changelist 
- Last year, when doing board bringup/chimera testing, we disabled the watchdog. Bringing back watchdog broke Chimera, since the chimera version of tasks was not petting watchdog.
- This PR removes `io_chimera_sleepIfTaskEnabled()` in favour of `io_chimera_block()` and `io_chimera_task()`.
  - `io_chimera_task` implements a simple watchdog pinging task.
  - `io_chimera_block` operates like `io_chimera_sleepIfTaskEnabled`, and sleeps the task if chimera is enabled.

### Testing Done
- [ ] Tested in BMS @DJ90864 

### Resolved Tickets

2024-11-14 01:37 UTC, Lucien950 commented
I think we need a far deeper fix for this. The watchdog code from before I just raw ported.

2024-11-14 01:40 UTC, Lucien950 commented
changes I think should be here:
1. refresh_watchdog removed in favour of bringing a reference to the watchdog into the watchdog monitor
2. refresh HAL watchdog only when there are no timeouts detected
3. if there are no watchdogs registered, then the watchdogs are vacuously fine, and so we should trigger a refresh
4. in chimera task, we trigger watchdog monitor on the vacuous case

2025-01-19 18:26 UTC, Lucien950 requested changes
can we close this? i think it's better if we should disable watchdog when chimera is running rather than infinitely petting it

2025-01-28 02:55 UTC, liam-ilan commented
Not going to happen - to be fixed in Chimera V2

2025-01-28 02:55 UTC, closed without merging