BMS Quintuna Board Bring Up
UBCFormulaElectric/Consolidated-Firmware pull request #1390
Opened 2024-11-24 01:02 UTC by KelmLelm

### Changelist 

### Testing Done

### Resolved Tickets

2024-11-26 21:33 UTC, Lucien950 requested changes
little more things

2024-12-07 15:39 UTC, KelmLelm commented on .vscode/tasks.json
> +                "quintuna_BMS.hex", "can_bus_load_quadruna"
Hey, sorry I got to this so late, how do you mean?

2025-01-02 06:06 UTC, Lucien950 commented on .vscode/tasks.json
> +                "quintuna_BMS.hex", "can_bus_load_quadruna"
good build target

2025-01-02 06:06 UTC, Lucien950 approved these changes
i like

2025-01-11 20:17 UTC, merged