ssm_bringup
UBCFormulaElectric/Consolidated-Firmware pull request #1391
Opened 2024-11-24 01:07 UTC by setaremalekiii

### Changelist 
Set up STM32 and CMake for SSM 
#
## Testing Done
None
### Resolved Tickets
None

2024-11-26 21:33 UTC, Lucien950 requested changes
lets get this compiling next saturday

2024-11-26 21:41 UTC, Lucien950 commented
also, please remember to create a stub tasks.cpp file

2025-01-19 08:48 UTC, setaremalekiii commented on firmware/dev/SSM/CMakeLists.txt
> +
so just move the embedded_binary to the end?

2025-01-19 20:22 UTC, Lucien950 requested changes

2025-01-19 20:22 UTC, Lucien950 commented on firmware/dev/SSM/CMakeLists.txt
> +     target_link_libraries("quintuna_SSM_jsoncan" PRIVATE "quintuna_SSM_stm32cube")
```suggestion
     target_link_libraries("quintuna_SSM_jsoncan" INTERFACE "quintuna_SSM_stm32cube")
```

2025-01-19 21:41 UTC, Lucien950 approved these changes

2025-01-20 20:14 UTC, merged