Move CMakeLists to repo root
UBCFormulaElectric/Consolidated-Firmware pull request #936
Opened 2023-07-28 02:42 UTC by gtaharaedmonds

### Summary

### Changelist 

### Testing Done

### Resolved Issues

### Checklist
*Please change `[ ]` to `[x]` when you are ready.*
- [ ] I have read and followed the code conventions detailed in [README.md](../README.md) (*This will save time for both you and the reviewer!*).
- [ ] If this pull request is longer then **500** lines, I have provided *explicit* justification in the summary above explaining why I *cannot* break this up into multiple pull requests (*Small PR's are faster and less painful for everyone involved!*).

2023-07-28 17:22 UTC, Lucien950 submitted a review, later dismissed
okie dokie

2023-07-28 17:27 UTC, will-chaba requested changes
On the Linux side, Clion has lost all build configurations. We stored the configurations as files, but annoyingly there is no "open existing configuration" option in the GUI, only a make new configuration option. Is there a configuration file we could edit directly to modify the paths rather than re-create all of them individually in the GUI?

EDIT: looks like you can copy the run configurations, from repo root `cp ./boards/.idea/runConfigurations/* .idea/runConfigurations` does the trick, but the directory is ignored by .gitignore so would have to be done locally on every machine. Not a problem, but needs to be documented. 

Once that's done I get my configurations back, but get some Cmake warnings:

```
/home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DPLATFORM=x86 -G "CodeBlocks - Unix Makefiles" -S /home/formulae/Documents/Consolidated-Firmware -B /home/formulae/Documents/Consolidated-Firmware/cmake-build-gtest
Platform: x86
CMake Error at /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/ExternalProject.cmake:2670 (message):
  At least one entry of URL is a path (invalid in a list)
Call Stack (most recent call first):
  /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/ExternalProject.cmake:3640 (_ep_add_download_command)
  CMakeLists.txt:15 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!
See also "/home/formulae/Documents/Consolidated-Firmware/cmake-build-gtest/_deps/googletest-subbuild/CMakeFiles/CMakeOutput.log".

CMake Error at /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/FetchContent.cmake:1076 (message):
  CMake step for googletest failed: 1
Call Stack (most recent call first):
  /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/FetchContent.cmake:1217:EVAL:2 (__FetchContent_directPopulate)
  /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/FetchContent.cmake:1217 (cmake_language)
  /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/FetchContent.cmake:1260 (FetchContent_Populate)
  CMakeLists.txt:65 (FetchContent_MakeAvailable)


-- Configuring incomplete, errors occurred!
See also "/home/formulae/Documents/Consolidated-Firmware/cmake-build-gtest/CMakeFiles/CMakeOutput.log".

[Failed to reload]
```

I can't really look into it right now but could dig deeper later to get to the bottom of this

2023-07-28 17:28 UTC, Lucien950 requested changes
Python Error:
```bash
Traceback (most recent call last):
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\generate_can_from_json.py", line 7, in <module>
    from src.json_parsing.json_can_parsing import JsonCanParser
Traceback (most recent call last):
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\generate_can_from_json.py", line 7, in <module>
Traceback (most recent call last):
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\json_parsing\json_can_parsing.py", line 8, in <module>
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\generate_can_from_json.py", line 7, in <module>
    from ..can_database import *
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\can_database.py", line 6, in <module>
    from src.json_parsing.json_can_parsing import JsonCanParser
    from src.json_parsing.json_can_parsing import JsonCanParser
Traceback (most recent call last):
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\json_parsing\json_can_parsing.py", line 8, in <module>
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\generate_can_from_json.py", line 7, in <module>
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\json_parsing\json_can_parsing.py", line 8, in <module>
    from strenum import StrEnum
ModuleNotFoundError: No module named 'strenum'
    from ..can_database import *
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\can_database.py", line 6, in <module>
    from src.json_parsing.json_can_parsing import JsonCanParser
    from ..can_database import *
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\json_parsing\json_can_parsing.py", line 8, in <module>
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\can_database.py", line 6, in <module>
    from strenum import StrEnum
ModuleNotFoundError: No module named 'strenum'
    from ..can_database import *
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\can_database.py", line 6, in <module>
    from strenum import StrEnum
ModuleNotFoundError: No module named 'strenum'
    from strenum import StrEnum
ModuleNotFoundError: No module named 'strenum'
Traceback (most recent call last):
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\generate_can_from_json.py", line 7, in <module>
    from src.json_parsing.json_can_parsing import JsonCanParser
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\json_parsing\json_can_parsing.py", line 8, in <module>
    from ..can_database import *
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\can_database.py", line 6, in <module>
    from strenum import StrEnum
ModuleNotFoundError: No module named 'strenum'
Traceback (most recent call last):
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\generate_can_from_json.py", line 7, in <module>
    from src.json_parsing.json_can_parsing import JsonCanParser
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\json_parsing\json_can_parsing.py", line 8, in <module>
    from ..can_database import *
  File "C:\Users\jessi\Documents\School\fsae\Consolidated-Firmware\scripts\codegen\jsoncan\src\can_database.py", line 6, in <module>
    from strenum import StrEnum
ModuleNotFoundError: No module named 'strenum'
mingw32-make.exe[3]: *** [BMS\CMakeFiles\BMS.elf.dir\build.make:125: BMS/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** [PDM\CMakeFiles\PDM.elf.dir\build.make:125: PDM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** [GSM\CMakeFiles\GSM.elf.dir\build.make:125: GSM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** [DCM\CMakeFiles\DCM.elf.dir\build.make:125: DCM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:365: BMS/CMakeFiles/BMS.elf.dir/all] Error 2
mingw32-make.exe[2]: *** Waiting for unfinished jobs....
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:417: GSM/CMakeFiles/GSM.elf.dir/all] Error 2
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:313: PDM/CMakeFiles/PDM.elf.dir/all] Error 2
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:287: DCM/CMakeFiles/DCM.elf.dir/all] Error 2
mingw32-make.exe[3]: *** [DIM\CMakeFiles\DIM.elf.dir\build.make:125: DIM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** [FSM\CMakeFiles\FSM.elf.dir\build.make:125: FSM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
```

2023-07-28 17:36 UTC, Lucien950 submitted a review, later dismissed
Error on Cmake build
```bash
Cannot get compiler information:
	Compiler exited with error code 1: C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe -xc -DARM_MATH_CM4 -DARM_MATH_MATRIX_CHECK -DARM_MATH_ROUNDING -DSTM32F412Rx -DUSE_HAL_DRIVER -D__packed=__attribute__((__packed__)) -D__weak=__attribute__((weak)) -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Drivers/STM32F4xx_HAL_Driver/Inc -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Middlewares/Third_Party/FreeRTOS/Source/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Drivers/CMSIS/Device/ST/STM32F4xx/Include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Drivers/CMSIS/Include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/config -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/streamports/Jlink_RTT/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/SEGGER_RTT -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/sbgECom/common -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/sbgECom/src -g -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mthumb-interwork -ffunction-sections -fdata-sections -g3 -fno-common -fmessage-length=0 -Wall -Wextra -pedantic -specs=nosys.specs -specs=nano.specs -Wdouble-promotion -Wshadow -Wundef -fstack-usage -Wconversion -Wno-unused-variable -Wno-unused-parameter -fpch-preprocess -v -dD -E
	gcc.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
	Using built-in specs.
	Reading specs from nosys.specs
	gcc.exe: error: nosys.specs: No such file or directory
	
	
	Compiler exited with error code 1: C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe -xc -DARM_MATH_CM4 -DARM_MATH_MATRIX_CHECK -DARM_MATH_ROUNDING -DSTM32F412Rx -DUSE_HAL_DRIVER -D__packed=__attribute__((__packed__)) -D__weak=__attribute__((weak)) -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Drivers/STM32F4xx_HAL_Driver/Inc -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Middlewares/Third_Party/FreeRTOS/Source/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Drivers/CMSIS/Device/ST/STM32F4xx/Include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/Drivers/CMSIS/Include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/config -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/streamports/Jlink_RTT/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/SEGGER_RTT -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/sbgECom/common -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/sbgECom/src -g -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mthumb-interwork -ffunction-sections -fdata-sections -g3 -fno-common -fmessage-length=0 -Wall -Wextra -pedantic -specs=nosys.specs -specs=nano.specs -Wdouble-promotion -Wshadow -Wundef -fstack-usage -Wconversion -Wno-unused-variable -Wno-unused-parameter -w -fpch-preprocess -v -dD -E
	gcc.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
	Using built-in specs.
	Reading specs from nosys.specs
	gcc.exe: error: nosys.specs: No such file or directory
	
	
	Compiler exited with error code 1: C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe -xc -DARM_MATH_CM4 -DARM_MATH_MATRIX_CHECK -DARM_MATH_ROUNDING -DSTM32F412Rx -DUSE_HAL_DRIVER -D__packed=__attribute__((__packed__)) -D__weak=__attribute__((weak)) -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Drivers/STM32F4xx_HAL_Driver/Inc -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Middlewares/Third_Party/FreeRTOS/Source/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Drivers/CMSIS/Device/ST/STM32F4xx/Include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Drivers/CMSIS/Include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/config -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/TraceRecorder/streamports/Jlink_RTT/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/SEGGER_RTT -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/sbgECom/common -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/shared/third_party/sbgECom/src -g -mcpu=cortex-m4 -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mthumb -mthumb-interwork -ffunction-sections -fdata-sections -g3 -fno-common -fmessage-length=0 -Wall -Wextra -pedantic -specs=nosys.specs -specs=nano.specs -Wdouble-promotion -Wshadow -Wundef -fstack-usage -Wconversion -Wno-unused-variable -Wno-unused-parameter -fpch-preprocess -v -dD -E
	gcc.exe: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead
	Using built-in specs.
	Reading specs from nosys.specs
	gcc.exe: error: nosys.specs: No such file or directory
	
	
	Compiler exited with error code 1: C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe -xc -DARM_MATH_CM4 -DARM_MATH_MATRIX_CHECK -DARM_MATH_ROUNDING -DSTM32F412Rx -DUSE_HAL_DRIVER -D__packed=__attribute__((__packed__)) -D__weak=__attribute__((weak)) -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Drivers/STM32F4xx_HAL_Driver/Inc -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Middlewares/Third_Party/FreeRTOS/Source/include -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -isystemC:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/Middlewares/Third_Party/FreeRT [...]

2023-07-28 18:16 UTC, gtaharaedmonds commented
> Error on Cmake build

@Lucien950 can you confirm you setup your CMake config as in the README? They will not be saved from previous project setup.
 It looks like CMake is trying to configure the x86 Windows compiler (MinGW) for the embedded targets: The `-mcpu` flag is only used on embedded targets, but in the error log it looks like it is being passed to MinGW GCC.
Did you modify your PATH variables or location of ARM Embedded Toolchain? The compiler binaries have to be on path or I think the compiler will use the system default, which in your case is MinGW.
Also, can you confirm the `-DPLATFORM=arm` is being passed to the embedded CMake target?
Also also I'd try deleting the generated `cmake-build-embedded` folder, and hitting Tools > CMake > Reset Cache and Reload Project since CMake can sometimes cache a bad state.

2023-07-28 18:22 UTC, gtaharaedmonds commented
CMake config: 
![image](https://github.com/UBCFormulaElectric/Consolidated-Firmware/assets/28274296/823088d9-22c3-4c04-b91e-1941c84391a4)

Path variables: 
![image](https://github.com/UBCFormulaElectric/Consolidated-Firmware/assets/28274296/45f586c9-6825-4d04-a99b-a35343d8395f)

2023-07-28 18:24 UTC, gtaharaedmonds commented
@will-chaba are you referring to CMake + Toolchain configs, or OpenOCD/GTest configs? 
You'll need to recreate the CMake + Toolchain configs yourself I believe, but I think I can move the run configs into the root.

2023-07-28 18:43 UTC, gtaharaedmonds commented
> @will-chaba are you referring to CMake + Toolchain configs, or OpenOCD/GTest configs? You'll need to recreate the CMake + Toolchain configs yourself I believe, but I think I can move the run configs into the root.

Okay yep added the OpenOCD run configurations back. GTest configs work for me automatically, and we weren't tracking them before.

2023-07-28 23:21 UTC, Lucien950 commented
Ok I am getting a new error:
```bash
The system cannot find the path specified.
The system cannot find the path specified.
mingw32-make.exe[3]: *** [DCM\CMakeFiles\DCM.elf.dir\build.make:73: DCM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
The system cannot find the path specified.
mingw32-make.exe[3]: *** [FSM\CMakeFiles\FSM.elf.dir\build.make:73: FSM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
mingw32-make.exe[3]: *** [PDM\CMakeFiles\PDM.elf.dir\build.make:73: PDM/Src/App/App_CanTx.c] Error 1
The system cannot find the path specified.
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
mingw32-make.exe[3]: *** [BMS\CMakeFiles\BMS.elf.dir\build.make:73: BMS/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
mingw32-make.exe[3]: *** [GSM\CMakeFiles\GSM.elf.dir\build.make:73: GSM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
mingw32-make.exe[3]: *** [PDM\CMakeFiles\PDM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/PDM/PDM.ioc.md5] Error 1
mingw32-make.exe[3]: *** [DCM\CMakeFiles\DCM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/DCM.ioc.md5] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:313: PDM/CMakeFiles/PDM.elf.dir/all] Error 2
mingw32-make.exe[2]: *** Waiting for unfinished jobs....
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:287: DCM/CMakeFiles/DCM.elf.dir/all] Error 2
The system cannot find the path specified.
mingw32-make.exe[3]: *** [FSM\CMakeFiles\FSM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/FSM/FSM.ioc.md5] Error 1
The system cannot find the path specified.
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:339: FSM/CMakeFiles/FSM.elf.dir/all] Error 2
The system cannot find the path specified.
The system cannot find the path specified.
mingw32-make.exe[3]: *** [DIM\CMakeFiles\DIM.elf.dir\build.make:73: DIM/Src/App/App_CanTx.c] Error 1
mingw32-make.exe[3]: *** Waiting for unfinished jobs....
mingw32-make.exe[3]: *** [BMS\CMakeFiles\BMS.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/BMS.ioc.md5] Error 1
mingw32-make.exe[3]: *** [GSM\CMakeFiles\GSM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/GSM/GSM.ioc.md5] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:365: BMS/CMakeFiles/BMS.elf.dir/all] Error 2
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:417: GSM/CMakeFiles/GSM.elf.dir/all] Error 2
The system cannot find the path specified.
mingw32-make.exe[3]: *** [DIM\CMakeFiles\DIM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DIM/DIM.ioc.md5] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:391: DIM/CMakeFiles/DIM.elf.dir/all] Error 2
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:269: CMakeFiles/all_arm_binaries.dir/rule] Error 2
mingw32-make.exe: *** [Makefile:123: all_arm_binaries] Error 2
```

2023-07-29 01:14 UTC, gtaharaedmonds commented
> Ok I am getting a new error:
> 
> ```shell
> The system cannot find the path specified.
> The system cannot find the path specified.
> mingw32-make.exe[3]: *** [DCM\CMakeFiles\DCM.elf.dir\build.make:73: DCM/Src/App/App_CanTx.c] Error 1
> mingw32-make.exe[3]: *** Waiting for unfinished jobs....
> The system cannot find the path specified.
> mingw32-make.exe[3]: *** [FSM\CMakeFiles\FSM.elf.dir\build.make:73: FSM/Src/App/App_CanTx.c] Error 1
> mingw32-make.exe[3]: *** Waiting for unfinished jobs....
> The system cannot find the path specified.
> The system cannot find the path specified.
> The system cannot find the path specified.
> mingw32-make.exe[3]: *** [PDM\CMakeFiles\PDM.elf.dir\build.make:73: PDM/Src/App/App_CanTx.c] Error 1
> The system cannot find the path specified.
> mingw32-make.exe[3]: *** Waiting for unfinished jobs....
> mingw32-make.exe[3]: *** [BMS\CMakeFiles\BMS.elf.dir\build.make:73: BMS/Src/App/App_CanTx.c] Error 1
> mingw32-make.exe[3]: *** Waiting for unfinished jobs....
> mingw32-make.exe[3]: *** [GSM\CMakeFiles\GSM.elf.dir\build.make:73: GSM/Src/App/App_CanTx.c] Error 1
> mingw32-make.exe[3]: *** Waiting for unfinished jobs....
> mingw32-make.exe[3]: *** [PDM\CMakeFiles\PDM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/PDM/PDM.ioc.md5] Error 1
> mingw32-make.exe[3]: *** [DCM\CMakeFiles\DCM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DCM/DCM.ioc.md5] Error 1
> mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:313: PDM/CMakeFiles/PDM.elf.dir/all] Error 2
> mingw32-make.exe[2]: *** Waiting for unfinished jobs....
> mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:287: DCM/CMakeFiles/DCM.elf.dir/all] Error 2
> The system cannot find the path specified.
> mingw32-make.exe[3]: *** [FSM\CMakeFiles\FSM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/FSM/FSM.ioc.md5] Error 1
> The system cannot find the path specified.
> mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:339: FSM/CMakeFiles/FSM.elf.dir/all] Error 2
> The system cannot find the path specified.
> The system cannot find the path specified.
> mingw32-make.exe[3]: *** [DIM\CMakeFiles\DIM.elf.dir\build.make:73: DIM/Src/App/App_CanTx.c] Error 1
> mingw32-make.exe[3]: *** Waiting for unfinished jobs....
> mingw32-make.exe[3]: *** [BMS\CMakeFiles\BMS.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/BMS/BMS.ioc.md5] Error 1
> mingw32-make.exe[3]: *** [GSM\CMakeFiles\GSM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/GSM/GSM.ioc.md5] Error 1
> mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:365: BMS/CMakeFiles/BMS.elf.dir/all] Error 2
> mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:417: GSM/CMakeFiles/GSM.elf.dir/all] Error 2
> The system cannot find the path specified.
> mingw32-make.exe[3]: *** [DIM\CMakeFiles\DIM.elf.dir\build.make:110: C:/Users/jessi/Documents/School/fsae/Consolidated-Firmware/boards/DIM/DIM.ioc.md5] Error 1
> mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:391: DIM/CMakeFiles/DIM.elf.dir/all] Error 2
> mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:269: CMakeFiles/all_arm_binaries.dir/rule] Error 2
> mingw32-make.exe: *** [Makefile:123: all_arm_binaries] Error 2
> ```

This is for the gtest configuration right? Try updating the submodules: `git submodules update --init --recursive`. I'm assuming you haven't changed anything locally too?

2023-07-29 05:11 UTC, Lucien950 commented
> 

This is for the binary build

2023-08-01 03:37 UTC, will-chaba commented on CMakeLists.txt
> +        DOWNLOAD_EXTRACT_TIMESTAMP 1
What is this line for? I had to comment it out to be able to build on linux, see error below

``` 
/home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DPLATFORM=x86 -G "CodeBlocks - Unix Makefiles" -S /home/formulae/Documents/test/Consolidated-Firmware -B /home/formulae/Documents/test/Consolidated-Firmware/cmake-build-gtest
Platform: x86
CMake Error at /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/ExternalProject.cmake:2670 (message):
  At least one entry of URL is a path (invalid in a list)
Call Stack (most recent call first):
  /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/ExternalProject.cmake:3640 (_ep_add_download_command)
  CMakeLists.txt:15 (ExternalProject_Add)


-- Configuring incomplete, errors occurred!
See also "/home/formulae/Documents/test/Consolidated-Firmware/cmake-build-gtest/_deps/googletest-subbuild/CMakeFiles/CMakeOutput.log".

CMake Error at /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/FetchContent.cmake:1076 (message):
  CMake step for googletest failed: 1
Call Stack (most recent call first):
  /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/FetchContent.cmake:1217:EVAL:2 (__FetchContent_directPopulate)
  /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/FetchContent.cmake:1217 (cmake_language)
  /home/formulae/Documents/clion-2022.2.3/bin/cmake/linux/share/cmake-3.23/Modules/FetchContent.cmake:1260 (FetchContent_Populate)
  CMakeLists.txt:65 (FetchContent_MakeAvailable)


-- Configuring incomplete, errors occurred!
See also "/home/formulae/Documents/test/Consolidated-Firmware/cmake-build-gtest/CMakeFiles/CMakeOutput.log".

[Failed to reload]
```

2023-08-01 03:51 UTC, will-chaba commented
> > @will-chaba are you referring to CMake + Toolchain configs, or OpenOCD/GTest configs? You'll need to recreate the CMake + Toolchain configs yourself I believe, but I think I can move the run configs into the root.
> 
> Okay yep added the OpenOCD run configurations back. GTest configs work for me automatically, and we weren't tracking them before.
> 
> @will-chaba building on linux locally works OK?

Building successfully on Linux after `DOWNLOAD_EXTRACT_TIMESTAMP 1` was removed from `FetchContent_Declare`, the steps are:
1. in Clion open Consolidated-Firmware/CmakeLists.txt as project
2. `git submodule update --init --recursive`
3. `pipenv update` (I actually ran `pipenv install && pipenv shell && pipenv update` but running update probably suffices)

2023-08-01 04:26 UTC, gtaharaedmonds commented
> > > @will-chaba are you referring to CMake + Toolchain configs, or OpenOCD/GTest configs? You'll need to recreate the CMake + Toolchain configs yourself I believe, but I think I can move the run configs into the root.
> > 
> > 
> > Okay yep added the OpenOCD run configurations back. GTest configs work for me automatically, and we weren't tracking them before.
> > @will-chaba building on linux locally works OK?
> 
> Building successfully on Linux after `DOWNLOAD_EXTRACT_TIMESTAMP 1` was removed from `FetchContent_Declare`, the steps are:
> 
> 1. in Clion open Consolidated-Firmware/CmakeLists.txt as project
> 2. Add Cmake options as in readme:
> 
> ```
> Name: embedded
> Build type: Debug
> CMake options: -DPLATFORM=arm
> 
> // Second CMake profile:
> Name: gtest
> Build type: Debug
> CMake options: -DPLATFORM=x86
> ```
> 
> (Also needed to set Generator to Unix Makefiles for both targets, maybe should update the Readme) 3. `git submodule update --init --recursive` 4. `pipenv update` (I actually ran `pipenv install && pipenv shell && pipenv update` but running update probably suffices) 5. reload cmake
> 
> Once the Cmake file loaded without errors, I did not need to manually set any build configurations
> 
> Once we have Windows building for Edwin, I'd like us to update the readme and at least point a reference on the wiki about how set up environment after change before we merge this in.

Ok we can just remove `DOWNLOAD_EXTRACT_TIMESTAMP`, I only added it to suppress an error. Out of curiosity, what's your Cmake version? Looks like `DOWNLOAD_EXTRACT_TIMESTAMP` is new in 3.24.

That's a good result though, I'm pretty sure that's basically what we have in the README right now.

2023-08-01 04:28 UTC, gtaharaedmonds commented
Ah just saw that you have 3.23, so that makes sense. Suppresses a warning I get, so fine just removing this right now:

```bash
CMake Warning (dev) at C:/Program Files/JetBrains/CLion 2023.1.2/bin/cmake/win/x64/share/cmake-3.25/Modules/FetchContent.cmake:1284 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
```

2023-08-07 06:08 UTC, will-chaba approved these changes
Looks like Linux is building find, can we create a document with our steps to get the system working for each platform before merging? (either readme or confluence is fine with me)

2023-08-07 07:36 UTC, gtaharaedmonds commented
> Looks like Linux is building find, can we create a document with our steps to get the system working for each platform before merging? (either readme or confluence is fine with me)

Setup should be identical to before, and also my other reorganization PR will change setup a lot, so let's leave it for now. There's a lot that needs fixing in the README -> We can make this part of the new onboarding docs.

2023-08-07 07:37 UTC, merged